apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
  - ytt:
      overlayContractV1:
        overlay.yml: |
          #@ load("@ytt:data", "data")
          #@ load("@ytt:overlay", "overlay")

          #@ if/end hasattr(data.values.existing.spec, "caBundle"):
          #@overlay/match by=overlay.all
          ---
          spec:
            #@overlay/remove
            insecureSkipTLSVerify:
    resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: apiregistration.k8s.io/v1beta1, kind: APIService}
      - apiVersionKindMatcher: {apiVersion: apiregistration.k8s.io/v1, kind: APIService}
